version: 1.0.{build}

branches:
  only:
    - master

image: Visual Studio 2017

clone_folder: c:\projects\middlewareDemo

environment:
  nodejs_version: "6"

install:
  - cd TestApp.Web
  - npm install
  - dotnet restore
  - dotnet build