version: 1.0.{build}

branches:
  only:
    - master

init:
  - git config --global core.autocrlf true

image: Visual Studio 2017

environment:
  nodejs_version: "6"
  CLI_VERSION: "1.0.0"

clone_folder: c:\projects\middlewareDemo

install:
  - dotnet --info
  - ps: @powershell -NoProfile -ExecutionPolicy unrestricted -Command "&([scriptblock]::Create((Invoke-WebRequest -useb 'https://dot.net/v1/dotnet-install.ps1'))) -Channel 2.0 -InstallDir C:\cli"
  - ps: Install-Product node 6
  - npm install -g npm
  - node --version
  - npm --version
  - dotnet --info

build_script:
  - cd TestApp.Web
  - npm install
  - set ASPNETCORE_ENVIRONMENT=Development
  - dotnet restore
  - dotnet build