version: 1.0.{build}

branches:
  only:
    - master

init:
  - git config --global core.autocrlf true

image: Visual Studio 2017

environment:
  nodejs_version: "6"

clone_folder: c:\projects\middlewareDemo

install:
  - cd TestApp.Web
  - ps: Install-Product node 6
  - npm install -g npm
  - node --version
  - npm --version
  - npm install
  - dotnet restore
  - dotnet build